# open splits and windows in current path
bind '"' split-window -v -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"
bind 'c' new-window -c "#{pane_current_path}"

# popup window
bind-key -T prefix T display-popup -E
