#! /usr/bin/env bash

# Reset OPTIND to ensure correct parsing in subsequent calls
OPTIND=1

while getopts a:v:p: flag; do
  case "$flag" in
    a) audio=${OPTARG}; echo "Audio set to: $audio";;
    v) video=${OPTARG}; echo "Video set to: $video";;
    p) playlist=${OPTARG}; echo "Playlist set to: $playlist";;
    *) echo "Invalid option: -$flag" >&2; exit 1;;
  esac
done

# Shift arguments to get rid of options processed by getopts
shift $((OPTIND - 1))

# Define save directory
SAVE_DIR="$HOME/Downloads/yt"

# Check for video or playlist and execute accordingly
if [[ -n $audio ]]; then
  echo "Downloading audio $audio..."
  yt-dlp --js-runtimes bun --cookies-from-browser firefox -x -P "$SAVE_DIR" -o "%(uploader)s/%(title)s.%(ext)s" "$audio"
elif [[ -n $video ]]; then
  echo "Downloading video $video..."
  yt-dlp --js-runtimes bun --cookies-from-browser firefox -P "$SAVE_DIR" -S "res:720" -o "%(uploader)s/%(title)s.%(ext)s" "$video"
elif [[ -n $playlist ]]; then
  echo "Downloading playlist $playlist..."
  yt-dlp --js-runtimes bun --cookies-from-browser firefox -P "$SAVE_DIR" --yes-playlist -S "res:720" -o "%(uploader)s/%(playlist)s/%(playlist_index)s-%(title)s.%(ext)s" "$playlist"
else
  echo "no input"
fi
